name: Action Sample

on:
  push:
    branches:
      - master
      - working
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: |
          echo "do ls"
          ls
