name: Action Sample

on:
  push:
    branches:
      - master
      - working
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: test actions
      - run: eco "test start"
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al

